---
- name: configure repository
  hosts: all
  tasks:
  	- name: Import a key from url
  	  rpm_key:
  	  	state: present
  	  	key: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release

  	- name: BaseOS
  	  yum_repository:
  	  	name: baseos-internal
  	  	description: Baseos Description
  	  	file: baseos
  	  	baseurl: http://content/rhel9.0/x86_64/dvd/BaseOS
  	  	gpgcheck: yes
  	  	gpgkey: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release
  	  	enabled: yes

  	- name: AppStream
  	  yum_repository:
  	  	name: baseos-internal
  	  	description: AppStream Description
  	  	file: baseos
  	  	baseurl: http://content/rhel9.0/x86_64/dvd/AppStream
  	  	gpgcheck: yes
  	  	gpgkey: http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release
  	  	enabled: yes